In [3]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\DELL\Desktop\GenAI Projects\RNN Project\rnn_venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3286, 1354, 3141, 9344],
 [3286, 1354, 3141, 4956],
 [3286, 566, 3141, 3994],
 [7919, 7566, 6873, 1462, 2330],
 [7919, 7566, 6873, 1462, 6660],
 [3925, 3286, 8898, 3141, 5620],
 [2579, 9179, 4742, 1462]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3286 1354 3141 9344]
 [   0    0    0    0 3286 1354 3141 4956]
 [   0    0    0    0 3286  566 3141 3994]
 [   0    0    0 7919 7566 6873 1462 2330]
 [   0    0    0 7919 7566 6873 1462 6660]
 [   0    0    0 3925 3286 8898 3141 5620]
 [   0    0    0    0 2579 9179 4742 1462]]


In [12]:
## feature representation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length,input_shape=(sent_length,)))
model.compile('adam','mse')

c:\Users\DELL\Desktop\GenAI Projects\RNN Project\rnn_venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
c:\Users\DELL\Desktop\GenAI Projects\RNN Project\rnn_venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [20]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step


array([[[-0.04590103, -0.0462622 ,  0.02919832, -0.02531339,
         -0.04344466,  0.03496471,  0.04173127, -0.00178224,
         -0.03197097,  0.03199447],
        [-0.04590103, -0.0462622 ,  0.02919832, -0.02531339,
         -0.04344466,  0.03496471,  0.04173127, -0.00178224,
         -0.03197097,  0.03199447],
        [-0.04590103, -0.0462622 ,  0.02919832, -0.02531339,
         -0.04344466,  0.03496471,  0.04173127, -0.00178224,
         -0.03197097,  0.03199447],
        [-0.04590103, -0.0462622 ,  0.02919832, -0.02531339,
         -0.04344466,  0.03496471,  0.04173127, -0.00178224,
         -0.03197097,  0.03199447],
        [ 0.01889329, -0.02162359, -0.00326409,  0.00982475,
          0.03825276, -0.01172192,  0.04013057,  0.01961802,
         -0.02382757,  0.00204366],
        [ 0.0420364 , -0.04093609, -0.03723379, -0.0344547 ,
         -0.01537202, -0.03007026, -0.03424348, -0.01234948,
          0.02201078, -0.00287567],
        [ 0.03652174, -0.01651628,  0.03862802,  0.0